= FSL Community BSP - Summit Edition

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir fsl-community-bsp
$: cd fsl-community-bsp
$: repo init -u https://github.com/SummitESP/fsl-community-bsp-platform.git -b morty
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To start the image build:

[source,console]
$: SDKMACHINE=x86_64 MACHINE=tsimx6 DISTRO=fslc-framebuffer source ./setup-environment build
$: git clone git@github.com:SummitESP/fsl-community-bsp-platform.git -b morty
$: cp fsl-community-bsp-platform/*.conf conf/
$: bitbake fsl-image-multimedia-full meta-toolchain-qt5

The root file system that can be used to create an SD card will be created in:

/build/tmp/deploy/images/tsimx6/fsl-image-multimedia-full-tsimx6.tar.bz2

The installable SDK is found here:

/build/tmp/deploy/sdk/tsimx6/fslc-framebuffer-glibc-x86_64-meta-toolchain-qt5-armv7at2hf-neon-toolchain-2.2.1.sh

You can use any directory to host your build.

The source code is checked out at `fsl-community-bsp/sources`.

== Contributing

To contribute to this layer you should send the patches for review to the mailing list.

Mailing list::
    https://lists.yoctoproject.org/listinfo/meta-freescale

Source code::
    https://github.com/Freescale/fsl-community-bsp-platform

When creating patches, please use something like:

[source,console]
$: git format-patch -s --subject-prefix='fsl-community-bsp-platform][PATCH' origin

When sending patches, please use something like:

[source,console]
$: git send-email --to meta-freescale@yoctoproject.org <generated patch>

== Using Development and Testing Branches

Replace the `repo init` command above with one of the following:

master:: For developers
+
[source,console]
$: repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b master

master-next:: For intrepid developers and testers
+
Patches are typically merged into master-next and then are merged into master after a testing and comment period. It's possible that master-next has something you want or need. But it's also possible that using master-next breaks something that was working before. Use with caution.

[source,console]
$: repo init -u https://github.com/Freescale/fsl-community-bsp-platform -b master-next
